/* Generated By:JavaCC: Do not edit this line. Analyzer.java */
package javaCC;
import structure.*;
import structure.types.*;
import structure.types.predicat.*;
import java.util.ArrayList;
        public class Analyzer implements AnalyzerConstants {
                public Commande c;

/*----------------------------------
-	MAIN
-----------------------------------*/
  static final public ArrayList execute() throws ParseException {
         Commande c=null; ArrayList l = new ArrayList();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CREATE:
      case DROP:
      case ALTER:
      case INSERT:
      case DELETE:
      case SELECT:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CREATE:
        c = create();
                                         l.add(c);
        break;
      case DROP:
        c = drop();
                                         l.add(c);
        break;
      case ALTER:
        c = alter();
                                         l.add(c);
        break;
      case INSERT:
        c = insert();
                                         l.add(c);
        break;
      case DELETE:
        c = delete();
                                         l.add(c);
        break;
      case SELECT:
        c = select();
                                         l.add(c);
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
          {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  static final public Predicat executePredicat() throws ParseException {
         {if (true) return def_pred();}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList executeAggr() throws ParseException {
         {if (true) return def_aggr();}
    throw new Error("Missing return statement in function");
  }

/*----------------------------------
-	COMMANDES
-----------------------------------*/
        /*-------------
	-	CREATE -OK
	---------------*/
  static final public Create create() throws ParseException {
         Create c;
    jj_consume_token(CREATE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACT:
      c = create_fact();
      break;
    case DIMENSION:
      c = create_dim();
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  static final public CreateFact create_fact() throws ParseException {
         ArrayList l, ll = new ArrayList(); Token t;
    jj_consume_token(FACT);
    t = jj_consume_token(NOM);
    jj_consume_token(OUVRANTE);
    l = def_attr();
                 CreateFact cf = new CreateFact(t.toString(), Commande.FACT,l);
    jj_consume_token(FERMANTE);
    jj_consume_token(CONNECT);
    jj_consume_token(TO);
    t = jj_consume_token(NOM);
                              ll.add(t.toString());
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(VIRG);
      t = jj_consume_token(NOM);
                                               ll.add(t.toString());
    }
    jj_consume_token(PTVIRG);
         cf.addConnections(ll);{if (true) return cf;}
    throw new Error("Missing return statement in function");
  }

  static final public CreateDimension create_dim() throws ParseException {
         ArrayList l, lhs; Token t;Hierarchy h;
    jj_consume_token(DIMENSION);
    t = jj_consume_token(NOM);
    jj_consume_token(OUVRANTE);
    l = def_attr();
                 CreateDimension cd = new CreateDimension(t.toString(), Commande.DIMENSION,l);
    jj_consume_token(FERMANTE);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WITH:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(WITH);
      jj_consume_token(HIERARCHY);
      t = jj_consume_token(NOM);
      jj_consume_token(OUVRANTE);
      l = def_lev();
                                      h= new Hierarchy (t.toString(), l);
      jj_consume_token(FERMANTE);
                 cd.ajoutHierarchy(h);
    }
    jj_consume_token(PTVIRG);
         {if (true) return cd;}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	DROP	-ok
	---------------*/
  static final public Drop drop() throws ParseException {
         Drop d =null;
    jj_consume_token(DROP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACT:
      d = drop_fact();
      break;
    case DIMENSION:
      d = drop_dim();
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return d;}
    throw new Error("Missing return statement in function");
  }

  static final public Drop drop_fact() throws ParseException {
         Token t;
    jj_consume_token(FACT);
    t = jj_consume_token(NOM);
    jj_consume_token(PTVIRG);
         {if (true) return new Drop(t.toString(), Commande.FACT);}
    throw new Error("Missing return statement in function");
  }

  static final public Drop drop_dim() throws ParseException {
         Token t;
    jj_consume_token(DIMENSION);
    t = jj_consume_token(NOM);
    jj_consume_token(PTVIRG);
         {if (true) return new Drop(t.toString(), Commande.DIMENSION);}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	ALTER	-OK a ameliorer sur alter_fact
	---------------*/
  static final public Alter alter() throws ParseException {
         Alter ca = null;
    jj_consume_token(ALTER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACT:
      ca = alter_fact();
      break;
    case DIMENSION:
      ca = alter_dim();
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return ca;}
    throw new Error("Missing return statement in function");
  }

  static final public Alter alter_fact() throws ParseException {
         Token t; ArrayList l;
    jj_consume_token(FACT);
    t = jj_consume_token(NOM);
                        Alter ca = new Alter (t.toString(), Commande.FACT);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DROP:
    case ADD:
    case CONNECT:
    case DISCONNECT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
        jj_consume_token(ADD);
        l = def_attr();
                                   ca.setAlteration(Alter.ADD);
                                                        ca.setAttributs(l);
        break;
      case DROP:
        jj_consume_token(DROP);
        t = jj_consume_token(NOM);
                                ca.setAlteration(Alter.DROP);
                                                ca.ajoutString(t.toString());
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[7] = jj_gen;
            break label_4;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                               ca.ajoutString(t.toString());
        }
        break;
      case CONNECT:
        jj_consume_token(CONNECT);
        jj_consume_token(TO);
        t = jj_consume_token(NOM);
                                       ca.setAlteration(Alter.CONNECT);
                                                                ca.ajoutString(t.toString());
        label_5:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[8] = jj_gen;
            break label_5;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                               ca.ajoutString(t.toString());
        }
        break;
      case DISCONNECT:
        jj_consume_token(DISCONNECT);
        jj_consume_token(TO);
        t = jj_consume_token(NOM);
                                          ca.setAlteration(Alter.DISCONNECT);
                                                                        ca.ajoutString(t.toString());
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[9] = jj_gen;
            break label_6;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                               ca.ajoutString(t.toString());
        }
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(PTVIRG);
         {if (true) return ca;}
    throw new Error("Missing return statement in function");
  }

  static final public Alter alter_dim() throws ParseException {
         Token t; ArrayList l; Alter ca=null;
    jj_consume_token(DIMENSION);
    t = jj_consume_token(NOM);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DROP:
    case ADD:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADD:
        jj_consume_token(ADD);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOM:
          l = def_attr();
                                       ca = new Alter(t.toString(), Commande.DIMENSION,Alter.ADD, l);
          break;
        case HIERARCHY:
                                  ca = new AlterHierarchy (t.toString(), Commande.DIMENSION,AlterHierarchy.ADD_HIERARCHY);
          jj_consume_token(HIERARCHY);
          t = jj_consume_token(NOM);
          jj_consume_token(OUVRANTE);
          l = def_lev();
                                                              Hierarchy h= new Hierarchy (t.toString(), l);
          jj_consume_token(FERMANTE);
                                 ((AlterHierarchy)ca).ajoutHierarchy(h);
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case DROP:
        jj_consume_token(DROP);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NOM:
                         ca = new Alter(t.toString(), Commande.DIMENSION,Alter.DROP);
          t = jj_consume_token(NOM);
                                         ca.ajoutString(t.toString());
          label_7:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case VIRG:
              ;
              break;
            default:
              jj_la1[13] = jj_gen;
              break label_7;
            }
            jj_consume_token(VIRG);
            t = jj_consume_token(NOM);
                                                       ca.ajoutString(t.toString());
          }
          break;
        case HIERARCHY:
                                  ca = new AlterHierarchy (t.toString(), Commande.DIMENSION,AlterHierarchy.DROP_HIERARCHY);
          jj_consume_token(HIERARCHY);
          t = jj_consume_token(NOM);
                                         ((AlterHierarchy)ca).ajoutHierarchy(new Hierarchy(t.toString(),null));
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(PTVIRG);
         {if (true) return ca;}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	INSERT	-OK
	---------------*/
  static final public Insert insert() throws ParseException {
         Insert ci;
    jj_consume_token(INSERT);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACT:
      ci = insert_fact();
      break;
    case DIMENSION:
      ci = insert_dim();
      break;
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return ci;}
    throw new Error("Missing return statement in function");
  }

  static final public InsertFact insert_fact() throws ParseException {
         Token t;String s;InsertFact cif=null;Predicat p;
    jj_consume_token(FACT);
    t = jj_consume_token(NOM);
    jj_consume_token(VALUES);
    jj_consume_token(OUVRANTE);
    s = def_une_valeur();
                                            cif = new InsertFact(t.toString(), Commande.FACT, s);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_8;
      }
      jj_consume_token(VIRG);
      s = def_une_valeur();
                                                   cif.ajoutValeur(s);
    }
    jj_consume_token(FERMANTE);
    jj_consume_token(CONNECT);
    jj_consume_token(TO);
    t = jj_consume_token(NOM);
    jj_consume_token(WHERE);
    p = def_pred();
                                               cif.ajoutConnect(t.toString(),p);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_9;
      }
      jj_consume_token(VIRG);
      t = jj_consume_token(NOM);
      jj_consume_token(WHERE);
      p = def_pred();
                                                     cif.ajoutConnect(t.toString(),p);
    }
    jj_consume_token(PTVIRG);
         {if (true) return cif;}
    throw new Error("Missing return statement in function");
  }

//ok
  static final public Insert insert_dim() throws ParseException {
         Token t;String s;
    jj_consume_token(DIMENSION);
    t = jj_consume_token(NOM);
                            Insert ci = new Insert (t.toString(), Commande.DIMENSION);
    jj_consume_token(VALUES);
    jj_consume_token(OUVRANTE);
    s = def_une_valeur();
                                            ci.ajoutValeur(s);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_10;
      }
      jj_consume_token(VIRG);
      s = def_une_valeur();
                                                          ci.ajoutValeur(s);
    }
    jj_consume_token(FERMANTE);
    jj_consume_token(PTVIRG);
         {if (true) return ci;}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	DELETE -OK
	---------------*/
  static final public Delete delete() throws ParseException {
         Delete d;
    jj_consume_token(DELETE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACT:
      d = del_fact();
      break;
    case DIMENSION:
      d = del_dim();
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return d;}
    throw new Error("Missing return statement in function");
  }

  static final public Delete del_fact() throws ParseException {
         Token t; Predicat p=null;
    jj_consume_token(FACT);
    t = jj_consume_token(NOM);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      jj_consume_token(WHERE);
      p = def_pred();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(PTVIRG);
         {if (true) return new Delete(t.toString(), Commande.FACT,p);}
    throw new Error("Missing return statement in function");
  }

  static final public Delete del_dim() throws ParseException {
         Token t; Predicat p=null;
    jj_consume_token(DIMENSION);
    t = jj_consume_token(NOM);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      jj_consume_token(WHERE);
      p = def_pred();
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(PTVIRG);
         {if (true) return new Delete(t.toString(), Commande.DIMENSION,p);}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	SELECT	-OK
	---------------*/
  static final public Select select() throws ParseException {
         Token t;ArrayList l;String s; Predicat p=null;
    jj_consume_token(SELECT);
    l = def_aggr();
                              Select cs = new Select (l);
    jj_consume_token(ROW);
    t = jj_consume_token(NOM);
                         cs.setNomRow(t.toString());
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WITH:
      jj_consume_token(WITH);
      t = jj_consume_token(NOM);
                                  cs.setWithRow(t.toString());
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OUVRANTE:
        jj_consume_token(OUVRANTE);
        t = jj_consume_token(NOM);
                                s= t.toString();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PT:
          jj_consume_token(PT);
          t = jj_consume_token(NOM);
                                                              s= s+t.toString();
          break;
        default:
          jj_la1[24] = jj_gen;
          ;
        }
                                         cs.ajoutRow(s);
        label_11:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[25] = jj_gen;
            break label_11;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                       s= t.toString();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PT:
            jj_consume_token(PT);
            t = jj_consume_token(NOM);
                                                                     s= s+t.toString();
            break;
          default:
            jj_la1[26] = jj_gen;
            ;
          }
                                         cs.ajoutRow(s);
        }
        jj_consume_token(FERMANTE);
        break;
      default:
        jj_la1[27] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    jj_consume_token(COLUMN);
    t = jj_consume_token(NOM);
                                 cs.setNomColumn(t.toString());
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WITH:
      jj_consume_token(WITH);
      t = jj_consume_token(NOM);
                                  cs.setWithColumn(t.toString());
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OUVRANTE:
        jj_consume_token(OUVRANTE);
        t = jj_consume_token(NOM);
                                s= t.toString();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PT:
          jj_consume_token(PT);
          t = jj_consume_token(NOM);
                                                              s= s+t.toString();
          break;
        default:
          jj_la1[29] = jj_gen;
          ;
        }
                                         cs.ajoutColumn(s);
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[30] = jj_gen;
            break label_12;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                       s= t.toString();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PT:
            jj_consume_token(PT);
            t = jj_consume_token(NOM);
                                                                     s= s+t.toString();
            break;
          default:
            jj_la1[31] = jj_gen;
            ;
          }
                                         cs.ajoutColumn(s);
        }
        jj_consume_token(FERMANTE);
        break;
      default:
        jj_la1[32] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(FROM);
    t = jj_consume_token(NOM);
                       cs.setNomFrom(t.toString());
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      jj_consume_token(WHERE);
      p = def_pred();
      break;
    default:
      jj_la1[34] = jj_gen;
      ;
    }
                                        cs.setWhere(p);
    jj_consume_token(PTVIRG);
         {if (true) return cs;}
    throw new Error("Missing return statement in function");
  }

/*----------------------------------
-	DEFINITIONS
-----------------------------------*/
//tdate renvoit une string, le prend comme token
  static final public String def_une_valeur() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOT:
                 Token t=null;String s="";
      jj_consume_token(QUOT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ENTIER:
        s = tdate();
        break;
      case NOM:
        t = jj_consume_token(NOM);
                                                                  s = s+t.toString();
        label_13:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case NOM:
            ;
            break;
          default:
            jj_la1[35] = jj_gen;
            break label_13;
          }
          t = jj_consume_token(NOM);
                                                          s = s+" "+t.toString();
        }
        break;
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(QUOT);
                         {if (true) return s;}
      break;
    case CHIFFRE:
      t = jj_consume_token(CHIFFRE);
                             {if (true) return t.toString();}
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	PREDICAT
	---------------*/
//pas de premiere parenthese gérée
//pas de or et and dans m parenthese
  static final public Predicat def_pred() throws ParseException {
         Predicat p=new Predicat ();; ElementAbstrait elmt;
    elmt = def_elmt(null);
                        p.setRacine(elmt);
                        {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

//pas encore ok
  static final public ElementAbstrait def_elmt(Liaison pere) throws ParseException {
         ElementAbstrait expr=null; Jointure j=null;
                Liaison l=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OUVRANTE:
      jj_consume_token(OUVRANTE);
      expr = def_elmt(pere);
      jj_consume_token(FERMANTE);
      break;
    case NOM:
      expr = def_jointure(pere);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
      case OR:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case AND:
          jj_consume_token(AND);
                               l = new Liaison (pere, Liaison.AND,expr);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OUVRANTE:
            jj_consume_token(OUVRANTE);
            expr = def_elmt(pere);
            jj_consume_token(FERMANTE);
                                                                            l.ajoutElmt(expr);
                                                                                                                        expr.setPere(l);
            break;
          case NOM:
            j = def_jointure(l);
                                                                 l.ajoutElmt(j);
                                                                                j.setPere(l);
            break;
          default:
            jj_la1[38] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          label_14:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case AND:
              ;
              break;
            default:
              jj_la1[39] = jj_gen;
              break label_14;
            }
            jj_consume_token(AND);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OUVRANTE:
              jj_consume_token(OUVRANTE);
              expr = def_elmt(pere);
              jj_consume_token(FERMANTE);
                                                                             l.ajoutElmt(expr);
                                                                                                                        expr.setPere(l);
              break;
            case NOM:
              j = def_jointure(l);
                                                         l.ajoutElmt(j);
                                                                                j.setPere(l);
              break;
            default:
              jj_la1[40] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
                 expr=l;
          break;
        case OR:
          jj_consume_token(OR);
                       l = new Liaison (pere, Liaison.OR,expr);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case OUVRANTE:
            jj_consume_token(OUVRANTE);
            expr = def_elmt(pere);
            jj_consume_token(FERMANTE);
                                                                    l.ajoutElmt(expr);
                                                                                                                        expr.setPere(l);
            break;
          case NOM:
            j = def_jointure(l);
                                                         l.ajoutElmt(j);
                                                                                j.setPere(l);
            break;
          default:
            jj_la1[41] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          label_15:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OR:
              ;
              break;
            default:
              jj_la1[42] = jj_gen;
              break label_15;
            }
            jj_consume_token(OR);
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case OUVRANTE:
              jj_consume_token(OUVRANTE);
              expr = def_elmt(pere);
              jj_consume_token(FERMANTE);
                                                                             l.ajoutElmt(expr);
                                                                                                                        expr.setPere(l);
              break;
            case NOM:
              j = def_jointure(l);
                                                         l.ajoutElmt(j);
                                                                                j.setPere(l);
              break;
            default:
              jj_la1[43] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
                 expr=l;
          break;
        default:
          jj_la1[44] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[45] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[46] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
          {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

//ok
  static final public Jointure def_jointure(Liaison pere) throws ParseException {
         Token t1, t2, t3; String s1="",s2="";
    t1 = jj_consume_token(NOM);
                  s1=t1.toString();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PT:
      jj_consume_token(PT);
      t1 = jj_consume_token(NOM);
                                                  s1=s1+"."+t1.toString();
      break;
    default:
      jj_la1[47] = jj_gen;
      ;
    }
    t3 = jj_consume_token(OPERATOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOM:
      t2 = jj_consume_token(NOM);
                                    s2=t2.toString();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PT:
        jj_consume_token(PT);
        t2 = jj_consume_token(NOM);
                                                                    s2=s2+"."+t2.toString();
        break;
      default:
        jj_la1[48] = jj_gen;
        ;
      }
      break;
    case QUOT:
    case CHIFFRE:
      s2 = def_une_valeur();
      break;
    default:
      jj_la1[49] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return new Jointure(pere,s1,s2,t3.toString());}
    throw new Error("Missing return statement in function");
  }

        /*-------------
	-	END PREDICAT
	---------------*/

//AVG, SUM, MAX, COUNT, SOM
//renvoit une ArrayList de String 
//ok
  static final public ArrayList def_aggr() throws ParseException {
         Token tA, t; String s; ArrayList l = new ArrayList();
    tA = jj_consume_token(FONCT);
    jj_consume_token(OUVRANTE);
    t = jj_consume_token(NOM);
                                 s = t.toString();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PT:
      jj_consume_token(PT);
      t = jj_consume_token(NOM);
                                                                s= s+t.toString();
      break;
    default:
      jj_la1[50] = jj_gen;
      ;
    }
                                s = tA.toString()+"("+s+")";
                                l.add(s);
    jj_consume_token(FERMANTE);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[51] = jj_gen;
        break label_16;
      }
      jj_consume_token(VIRG);
      tA = jj_consume_token(FONCT);
      jj_consume_token(OUVRANTE);
      t = jj_consume_token(NOM);
                                 s = t.toString();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PT:
        jj_consume_token(PT);
        t = jj_consume_token(NOM);
                                                                s= s+t.toString();
        break;
      default:
        jj_la1[52] = jj_gen;
        ;
      }
                                s = tA.toString()+"("+s+")";
                                l.add(s);
      jj_consume_token(FERMANTE);
    }
         {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

/*renvoit une ArrayList d'attributs*/
//ok
  static final public ArrayList def_attr() throws ParseException {
         Token t; Attribut att;
        ArrayList l=new ArrayList();
    t = jj_consume_token(NOM);
    att = def_dom();
                        att.setNom(t.toString());
                        l.add(att);
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRG:
        ;
        break;
      default:
        jj_la1[53] = jj_gen;
        break label_17;
      }
      jj_consume_token(VIRG);
      t = jj_consume_token(NOM);
      att = def_dom();
                        att.setNom(t.toString());
                        l.add(att);
    }
          {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

/*renvoit un attribut typé mais sans nom*/
//ok
  static final public Attribut def_dom() throws ParseException {
         Attribut att=null;Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DATE:
      jj_consume_token(DATE);
                att = new Attribut(Attribut.DATE);
      break;
    case NUMBER:
      jj_consume_token(NUMBER);
      jj_consume_token(OUVRANTE);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHIFFRE:
        t = jj_consume_token(CHIFFRE);
                                                String s = t.toString();int pos;
                                                                if ((pos=s.indexOf(",")) !=0)
                                                                {
                                                                        att = new Attribut (Attribut.NUMBER, Integer.parseInt(s.substring(0,pos)));
                                                                        att.setPrecision(Integer.parseInt(s.substring(pos+1)));
                                                                }else{
                                                                        att = new Attribut (Attribut.NUMBER,Integer.parseInt(s));
                                                                }
        break;
      case ENTIER:
        t = jj_consume_token(ENTIER);
                                              att = new Attribut (Attribut.NUMBER, Integer.parseInt(t.toString()));
        break;
      default:
        jj_la1[54] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(FERMANTE);
      break;
    case VARCHAR:
      jj_consume_token(VARCHAR);
      jj_consume_token(OUVRANTE);
      t = jj_consume_token(ENTIER);
                                                   att = new Attribut(Attribut.VARCHAR, Integer.parseInt(t.toString()));
      jj_consume_token(FERMANTE);
      break;
    default:
      jj_la1[55] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return att;}
    throw new Error("Missing return statement in function");
  }

//ArrayList de levels
//ok
  static final public ArrayList def_lev() throws ParseException {
         ArrayList l = new ArrayList(); Token t;Level level;
    label_18:
    while (true) {
      jj_consume_token(LEVEL);
      t = jj_consume_token(NOM);
                        level = new Level(t.toString());
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OUVRANTE:
        jj_consume_token(OUVRANTE);
        t = jj_consume_token(NOM);
                                 level.ajoutAttFaible(t.toString());
        label_19:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case VIRG:
            ;
            break;
          default:
            jj_la1[56] = jj_gen;
            break label_19;
          }
          jj_consume_token(VIRG);
          t = jj_consume_token(NOM);
                                        level.ajoutAttFaible(t.toString());
        }
        jj_consume_token(FERMANTE);
        break;
      default:
        jj_la1[57] = jj_gen;
        ;
      }
                 l.add(level);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEVEL:
        ;
        break;
      default:
        jj_la1[58] = jj_gen;
        break label_18;
      }
    }
         {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

/*----------------------------------
-	TYPES 
-----------------------------------*/
//pour l'instant, retourne une string
  static final public String tdate() throws ParseException {
         String dat=""; Token t;
    t = jj_consume_token(ENTIER);
                   dat= t.toString();
    jj_consume_token(SLASH);
    t = jj_consume_token(ENTIER);
                          dat=dat+"-"+ t.toString();
    jj_consume_token(SLASH);
    t = jj_consume_token(ENTIER);
                          dat=dat+"-"+ t.toString();
         {if (true) return dat;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  static public AnalyzerTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[59];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_0();
      jj_la1_1();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x1760,0x1760,0x22000,0x80000000,0x8000,0x22000,0x22000,0x80000000,0x80000000,0x80000000,0x3000c0,0x3000c0,0x10000,0x80000000,0x10000,0xc0,0xc0,0x22000,0x80000000,0x80000000,0x80000000,0x22000,0x800000,0x800000,0x40000000,0x80000000,0x40000000,0x8000000,0x8000,0x40000000,0x80000000,0x40000000,0x8000000,0x8000,0x800000,0x0,0x0,0x0,0x8000000,0x2000000,0x8000000,0x8000000,0x4000000,0x8000000,0x6000000,0x6000000,0x8000000,0x40000000,0x40000000,0x0,0x40000000,0x80000000,0x40000000,0x80000000,0x0,0x0,0x80000000,0x8000000,0x4000,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x200,0x0,0x200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x200,0x280,0x101,0x200,0x0,0x200,0x200,0x0,0x200,0x0,0x0,0x200,0x0,0x0,0x301,0x0,0x0,0x0,0x0,0x180,0x70,0x0,0x0,0x0,};
   }

  public Analyzer(java.io.InputStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalyzerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  public Analyzer(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalyzerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  public Analyzer(AnalyzerTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  public void ReInit(AnalyzerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 59; i++) jj_la1[i] = -1;
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  static public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[42];
    for (int i = 0; i < 42; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 59; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 42; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

        }
