/* Generated By:JavaCC: Do not edit this line. AnalyzerConstants.java */
package javaCC;

public interface AnalyzerConstants {

  int EOF = 0;
  int CREATE = 5;
  int DROP = 6;
  int ADD = 7;
  int ALTER = 8;
  int INSERT = 9;
  int DELETE = 10;
  int VALUES = 11;
  int SELECT = 12;
  int FACT = 13;
  int LEVEL = 14;
  int WITH = 15;
  int HIERARCHY = 16;
  int DIMENSION = 17;
  int ROW = 18;
  int COLUMN = 19;
  int CONNECT = 20;
  int DISCONNECT = 21;
  int TO = 22;
  int WHERE = 23;
  int FROM = 24;
  int AND = 25;
  int OR = 26;
  int OUVRANTE = 27;
  int FERMANTE = 28;
  int PTVIRG = 29;
  int PT = 30;
  int VIRG = 31;
  int QUOT = 32;
  int SLASH = 33;
  int OPERATOR = 34;
  int FONCT = 35;
  int DATE = 36;
  int VARCHAR = 37;
  int NUMBER = 38;
  int ENTIER = 39;
  int CHIFFRE = 40;
  int NOM = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\"create\"",
    "\"drop\"",
    "\"add\"",
    "\"alter\"",
    "\"insert into\"",
    "\"delete from\"",
    "\"values\"",
    "\"select\"",
    "\"fact\"",
    "\"level\"",
    "\"with\"",
    "\"hierarchy\"",
    "\"dimension\"",
    "\"row\"",
    "\"column\"",
    "\"connect\"",
    "\"disconnect\"",
    "\"to\"",
    "\"where\"",
    "\"from\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"\\\'\"",
    "\"/\"",
    "<OPERATOR>",
    "<FONCT>",
    "\"date\"",
    "\"varchar\"",
    "\"number\"",
    "<ENTIER>",
    "<CHIFFRE>",
    "<NOM>",
  };

}
